import streamlit as st
import asyncio
import sys
import socket
import uuid
import time

# Windows-specific fix for asyncio DNS and connection noise
if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    from asyncio.proactor_events import _ProactorBasePipeTransport
    
    def patched_call_connection_lost(self, exc):
        try:
            self._sock.shutdown(socket.SHUT_RDWR)
        except (ConnectionResetError, OSError):
            pass 
        self._call_connection_lost_orig(exc)

    if not hasattr(_ProactorBasePipeTransport, "_call_connection_lost_orig"):
        _ProactorBasePipeTransport._call_connection_lost_orig = _ProactorBasePipeTransport._call_connection_lost
        _ProactorBasePipeTransport._call_connection_lost = patched_call_connection_lost

from ui.state import init_state, add_message, get_messages
from ui.layout import render_main_layout
from ui.components import render_prompt_guide
from core.orchestrator import orchestrator
from core.logger import app_logger
from core.errors import AllProvidersFailedError

# Set page config first
st.set_page_config(
    page_title="Multimodal AI Studio",
    page_icon="✨",
    layout="wide",
    initial_sidebar_state="expanded",
)

async def process_request(prompt: str, target_output: str, params: dict, uploaded_file=None):
    try:
        input_type = st.session_state.get("current_input_mode", "Text").lower()
        
        app_logger.info(f"UI: {input_type} → {target_output}")

        image_bytes = None
        if uploaded_file and input_type == "image":
            image_bytes = uploaded_file.getvalue()
        
        video_bytes = None
        if uploaded_file and input_type == "video":
            video_bytes = uploaded_file.getvalue()

        # Call the orchestrator
        result = await orchestrator.generate(
            prompt=prompt,
            input_type=input_type,
            output_type=target_output.lower(),
            image_bytes=image_bytes,
            video_bytes=video_bytes,
            temperature=params.get("temperature", 0.7),
            max_tokens=params.get("max_tokens", 2048),
            video_style=params.get("video_style", "Natural")
        )
        
        # Determine content summary for media results
        content = result.content
        media_path = None
        media_type = None
        
        if result.content_type == "storyboard":
            fallback_reason = ""
            if result.metadata.get("message"):
                fallback_reason = f"\n\nℹ️ *{result.metadata['message']}*"
            
            content = f"🎬 **AI Cinematic Storyboard**\n\n**Storyboard Fallback — real video providers unavailable.**{fallback_reason}\n\n{result.content}"
            media_type = "storyboard"
        elif result.content_type != "text":
            if result.metadata.get("is_real_video"):
                 provider_label = result.provider.upper()
                 content = f"✅ **Real Video Generated by {provider_label}**\n\nGenerated video based on your prompt."
            else:
                 content = f"Generated {result.content_type} based on your prompt."

            media_path = result.content
            media_type = result.content_type
            
        add_message(
            "assistant", 
            content, 
            media_path=media_path, 
            media_type=media_type, 
            provider=result.provider,
            model=result.model,
            trace_id=result.trace_id,
            fallback_used=result.fallback_used,
            failed_providers=result.failed_providers,
            latency=result.latency,
            input_type=result.input_type,
            output_type=result.output_type,
            metadata=result.metadata
        )
        return True

    except AllProvidersFailedError as e:
        app_logger.error(f"UI Error: All providers failed. {e}")
        
        # Build concise summaries for UI
        summaries = []
        technical_details = []
        for f in e.failures:
            provider = f['provider']
            model = f.get('model', 'N/A')
            msg = f['message']
            err_type = f.get('error', 'Error')
            
            # Create concise summary
            summary = f"**{provider}** ({model}): "
            if "auth" in err_type.lower() or "401" in msg:
                summary += "Invalid or expired API Key."
            elif "credit" in err_type.lower() or "billing" in msg.lower() or "402" in msg:
                summary += "Insufficient credits / Billing issue."
            elif "moderation" in err_type.lower() or "rejected" in msg.lower() or "safety" in msg.lower():
                summary += "Content rejected by safety filters."
            elif "quota" in msg.lower() or "429" in msg or "RateLimit" in err_type:
                summary += "Quota exceeded / Rate limited."
            elif "NetworkDNSError" in err_type or "dns" in msg.lower() or "getaddrinfo" in msg.lower():
                summary += "Network unreachable or DNS failure."
            elif "timeout" in err_type.lower():
                summary += "Request timed out."
            else:
                summary += f"Unexpected error: {err_type}"
            
            summaries.append(summary)
            technical_details.append(f"### {provider} ({model})\n**Error Type:** {err_type}\n**Raw Message:**\n```\n{msg}\n```")

        failure_summary_text = "\n".join(summaries)
        full_tech_details = "\n\n".join(technical_details)
        trace_id = getattr(e, 'trace_id', 'Unknown')
        
        # Check if it was a vision route
        input_type = st.session_state.get("current_input_mode", "Text")
        target_output = params.get("target_output", "Text")
        
        if input_type in ["Image", "Video"] and target_output == "Text":
            error_title = "❌ **Vision Analysis Unavailable**"
            error_desc = "Image analysis could not be completed because all configured providers are unavailable due to quota, credits, or network issues."
        else:
            error_title = "❌ **All Providers Failed**"
            error_desc = "The system attempted several routes but none succeeded."

        with st.chat_message("assistant"):
            st.markdown(error_title)
            st.markdown(error_desc)
            st.markdown("### Attempted Providers:")
            st.markdown(failure_summary_text)
            st.markdown(f"**Trace ID:** `{trace_id}`")
            
            with st.expander("🔍 View Full Technical Details"):
                st.markdown(full_tech_details)
                st.info("Full tracebacks are available in `logs/errors.log`.")
        
        # We don't use add_message here because we've already rendered it manually 
        # to use the expander, but we should add it to history for state consistency
        # However, expander doesn't persist well in history strings, so we store a flat version
        add_message(
            "assistant", 
            f"{error_title}\n\n{error_desc}\n\n{failure_summary_text}\n\nTrace ID: {trace_id}"
        )

        return False
    except Exception as e:
        error_msg = str(e)
        app_logger.critical(f"🛑 [PROCESS ERROR]: {error_msg}")
        add_message("assistant", f"❌ **System Error:** {error_msg}")
        return False

def main():
    init_state()
    params = render_main_layout()
    
    # Retrieve uploaded file
    uploaded_file = None
    current_mode = st.session_state.get("current_input_mode", "Text")
    
    if current_mode == "Image":
        uploaded_file = st.session_state.get("sidebar_img_upload")
    elif current_mode == "Video":
        uploaded_file = st.session_state.get("sidebar_vid_upload")

    render_prompt_guide()
    prompt = st.chat_input(f"Send a message ({current_mode} mode)...")

    if prompt:
        # VALIDATION: Check for media if not in Text mode
        if current_mode == "Image" and not uploaded_file:
            st.warning("⚠️ Please upload an image before sending this request.")
            return
        if current_mode == "Video" and not uploaded_file:
            st.warning("⚠️ Please upload a video before sending this request.")
            return

        add_message("user", prompt)
        
        with st.chat_message("assistant"):
            status_container = st.empty()
            with status_container.status(f"🚀 Processing {current_mode} → {params['target_output']}...", expanded=True) as status:
                st.write("🔗 Initializing fallback-ready engine...")
                
                # In Streamlit, we need to handle the event loop carefully
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
                try:
                    loop.run_until_complete(process_request(prompt, params['target_output'], params, uploaded_file))
                finally:
                    loop.close()
                
                status.update(label="✅ Task Complete!", state="complete", expanded=False)
                
        st.rerun()

if __name__ == "__main__":
    main()
